Feat: allow users to change dotenv file with env var
museofficial/muse pull request #1040
Opened 2024-07-06 00:05 UTC by JoaoCostaIFG

This facilitates the usage of docker secrets for the keys/tokens.

For example on a `docker-compose.yml` file:

```yaml
muse:
  image: codetheweb/muse:latest
  container_name: muse
  secrets:
    - muse_env
  environment:
    - ENV_FILE=/run/secrets/muse_env
  restart: unless-stopped
  
secrets:
  muse_env:
    file: /usr/local/etc/muse_env
```

- [ ] I updated the changelog

2024-07-06 00:06 UTC, JoaoCostaIFG commented
Not sure if I should update the changelog. Please let me know.

2024-07-18 04:46 UTC, codetheweb commented
Cool!

1. Let's default `ENV_FILE` to `/config` in the Dockerfile so there's a sensible default.
2. We should also document this in the README.

Thank you!

2024-10-28 15:17 UTC, Codixer commented
@JoaoCostaIFG 
Do you still want this PR to be processed?

2024-10-28 16:17 UTC, JoaoCostaIFG commented
> @JoaoCostaIFG Do you still want this PR to be processed?

I haven't been using discord, so I completely forgot about this PR. Sorry about that.
I just pushed the requested changes.
Let me know if there's anything else that needs work.

2024-10-28 16:20 UTC, codetheweb commented
#### :package: :robot: A new release has been made for this pull request.

To play around with this PR, pull `ghcr.io/museofficial/muse:pr-1040`.

Images are available for x86_64 and ARM64.

> Latest commit: 55a1ce664821eb1405cb07d8c26f65b80722aa5c
<!-- Sticky Pull Request Commentpr-release -->

2024-10-28 21:53 UTC, Codixer requested changes
See review

2024-10-28 21:53 UTC, Codixer commented on Dockerfile
@JoaoCostaIFG Could you fix the legacy key perchance? See comment/warning by the Actions

2024-10-28 22:36 UTC, JoaoCostaIFG commented on Dockerfile
Doné :)

2024-10-29 08:13 UTC, Codixer commented on Dockerfile
Thanks!

2024-10-29 08:13 UTC, Codixer commented
LGTM

2024-10-29 08:14 UTC, Codixer approved these changes

2024-10-29 08:15 UTC, merged

2024-10-29 09:26 UTC, codetheweb commented
🚀 Released in [Release v2.9.5](https://github.com/museofficial/muse/releases/tag/v2.9.5).