Pull Request: ESLint Configuration, Dependency Updates, and Type Safety Improvements
museofficial/muse pull request #1178
Opened 2024-12-28 08:36 UTC by soulwax

## Description

I have worked for quite a while on this project, albeit 80% of it went into (learning how to) configuring eslint in an already established environment. This PR comes with a few enhancements to the project, focusing on code quality, security, and maintainability. The main changes include:

ESLint Configuration: A new flat ESLint configuration file (`eslint.config.js`) has been added to the project. This configuration defines a set of linting rules to ensure consistent code style and catch potential issues early in the development process. The linter has been run on the codebase, and any identified problems have been fixed.

Dependency Updates: Critical dependencies have been updated to their latest versions while I also tested everything thoroughly in order to not break anything. The updates address security vulnerabilities and some of them came from dependabot out of the blue after forking your original. I tested mainly on unix OSes using node v18 and v20 as you intended from what I took out of your dovcs. Project works fine with v18, v20 is problematic on windows due to discordjs/opus but that's a known problem not related to muse.

Type Safety Improvements: To enhance type safety, occurrences of `any` have been converted to `unknown` where appropriate. This should help catch potential type-related issues down the line.

Husky Configuration: The Husky configuration has been resolved to facilitate easier contributions to the project. Any future contributors shouldn't have husky serve as a gatekeeper against linting problems.

## Motivation and Context

I like and use a fork of the bot myself for quite some time now albeit I am rewriting a different approach from scratch either.

## How Has This Been Tested?

The changes introduced in this pull request have been thoroughly enough tested to ensure that the project's functionality remains intact and there are only wins for everyone involved, be it non techies or active cooooontributors. The ESLint rules have been applied to the codebase, and any identified issues have been resolved.

## Types of Changes, let's try out those checkboxes lol

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Related Issues

- Resolves: broadband

## Acknowledgements

Max Isom's great work for a not sucking discord music bot.

2024-12-28 08:40 UTC, codetheweb commented
#### :package: :robot: A new release has been made for this pull request.

To play around with this PR, pull `ghcr.io/museofficial/muse:pr-1178`.

Images are available for x86_64 and ARM64.

> Latest commit: 707243f3ad80b73985bfdc82af6cfee8687ce200
<!-- Sticky Pull Request Commentpr-release -->

2024-12-29 08:20 UTC, soulwax commented
Can you elaborate? Did you abandon the project, or only release docker images now? Otherwise why not just merge the PR?

2024-12-29 20:20 UTC, Codixer commented
@soulwax that message is from a bot, not the creator himself. Look at uhhhhh, #1063.

2025-01-05 23:04 UTC, Codixer requested changes
While I can understand some changes, almost half to the entire code here looks like it's been thrown through a fault checker with intellisense and/or ran through CoPilot/ChatGPT. 

What's the use of all these changes (commented ones).

2025-01-05 23:04 UTC, Codixer commented on package.json
Has the bot been checked to still work with all these dependencies? I tried updating some a while back and they still broke the functionality of the bot.

2025-01-05 23:04 UTC, Codixer commented on src/services/add-query-to-queue.ts
So I'm assuming here that several variables have been changed and or replaced. What about the code it was attached to?

2025-01-05 23:04 UTC, Codixer commented on src/services/youtube-api.ts
> +      async (...args) => ytsr(args[0] as string, args[1] as ytsr.Options),
What made this change come up?

2025-01-24 23:12 UTC, closed without merging